[build]
  command = "npm run build"
  publish = "build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

  EMAILJS_USER = "@emailjs_user"
  SERVICE_ID = "@service_id"
  TEMPLATE_ID = "@template_id"

[[headers]]
  for = "/build/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"